=== cedricchristoph/cedric_LND/TRIM2/UD7/Dossier/Practica_Final/clinica_veterinaria.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="clinicaveterinaria">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="codigo" type="xs:string"/>
				<xs:element name="cliente" maxOccurs="unbounded" type="cliente"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="cliente">
		<xs:sequence>
			<xs:element name="nombre" type="xs:string"/>
			<xs:element name="apellidos" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="animal" type="animal" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="animal">
		<xs:attribute  name="especie">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="perro"></xs:enumeration>
					<xs:enumeration value="gato"></xs:enumeration>
					<xs:enumeration value="reptil"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="nombre" type="xs:string"/>
		<xs:attribute name="edad">
			<xs:simpleType>
				<xs:restriction base="xs:integer">
					<xs:minInclusive value="0"/>
					<xs:maxInclusive value="15"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="raza" type="xs:string"></xs:attribute>
		<xs:attribute name="sexo">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="H"/>
					<xs:enumeration value="M"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== cedricchristoph/cedric_LND/TRIM2/UD7/Dossier/Practica_Final/clinicaveterinaria.xml
<?xml version="1.0" encoding="UTF-8"?>

<clinicaveterinaria xsi:noNamespaceSchemaLocation="C:\Users\Inf2\Documents\Practica_Final\clinica_veterinaria.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<codigo>H567Y</codigo>
	<cliente>
		<nombre>Elena</nombre>
		<apellidos>VÃ¡zquez</apellidos>
		<animal especie="perro" nombre="Lili" edad="12" raza="algo" sexo="H"/>
	</cliente>

	<cliente>
		<nombre>Cedric</nombre>
		<apellidos>Christoph</apellidos>
		<animal especie="perro" nombre="Wauf" edad="12" raza="Husky" sexo="M"/>
	</cliente>
	
	<cliente>
		<nombre>Kairon</nombre>
		<animal especie="gato" nombre="Sisi" edad="4" raza="algo" sexo="H"/>
	</cliente>

</clinicaveterinaria>
