=== cedricchristoph/cedric_LND/TRIM2/UD7/Tareas/Tarea7_1/olimpiadas.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="olimpiadas" type="tipoolimpiadas"/>
	<xs:complexType name="tipoolimpiadas">
		<xs:sequence>
			<xs:element name="aÃ±o" type="xs:integer"/>
			<xs:element name="sede" type="xs:string"/>
			<xs:element name="deporte" type="tipodeporte" minOccurs="2" maxOccurs="10"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="tipodeporte">
		<xs:sequence>
			<xs:element name="ganador" type="tipoganador" minOccurs="1" maxOccurs="3"/>
		</xs:sequence>
		<xs:attribute name="nombre" type="xs:string"/>
		<xs:attribute name="modalidad">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="Masculino"/>
					<xs:enumeration value="Femenino"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>

	</xs:complexType>
	<xs:complexType name="tipoganador">
	
		<xs:sequence>
			<xs:element name="nombre" type="xs:string"/>
			<xs:element name="pais" type="xs:string"/>
			<xs:element name="medalla">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="oro"/>
						<xs:enumeration value="plata"/>
						<xs:enumeration value="bronce"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="discapacidad" type="xs:boolean" default="false"/>
	</xs:complexType>

</xs:schema>

=== cedricchristoph/cedric_LND/TRIM2/UD7/Tareas/Tarea7_1/londres.xml
<?xml version="1.0" encoding="UTF-8"?>



<olimpiadas xmlns="http://www.misitio.com" xmlns:xsi="http://www.w3.org/TR/xmlschema-1/" xsi:schemaLocation="olimpiadas.xsd">
	<año>2012</año>
	<sede>Londres</sede>
	<deporte nombre="Tiro con arco" modalidad="Masculino">
		<ganador>
			<nombre>Furukawa</nombre>
			<pais>Japón</pais>
			<medalla>oro</medalla>
		</ganador>
		<ganador discapacidad="true">
			<nombre>Delgado</nombre>
			<pais>Colombia</pais>
			<medalla>plata</medalla>
		</ganador>
		<ganador discapacidad="true">
			<nombre>Smith</nombre>
			<pais>Inglaterra</pais>
			<medalla>bronce</medalla>
		</ganador>
	</deporte>
	<deporte nombre="Natación" modalidad="Femenino">
		<ganador>
			<nombre>Paulova</nombre>
			<pais>Polonia</pais>
			<medalla>oro</medalla>
		</ganador>
		<ganador>
			<nombre>Fiorella</nombre>
			<pais>Italia</pais>
			<medalla>plata</medalla>
		</ganador>
		<ganador>
			<nombre>Valázquez</nombre>
			<pais>Chile</pais>
			<medalla>bronce</medalla>
		</ganador>
	</deporte>
</olimpiadas>
