=== cedricchristoph/cedric_LND/TRIM2/UD7/Tareas/Tarea7_1/olimpiadas.dtd
<!ELEMENT  olimpiadas(año,sede,deporte+)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT sede(#PCDATA)>
<!ELEMENT deporte (ganador+)>
<!ATTLIST deporte nombre CDATA>
<!ATTLIST deporte modalidad ("Masculino"|"Femenino")>
<!ELEMENT ganador (nombre,pais,medalla)>
<!ATTLIST ganador discapacidad CDATA>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT medalla (#PCDATA)>

=== cedricchristoph/cedric_LND/TRIM2/UD7/Tareas/Tarea7_1/londres_dtd.xml
<? xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE olimpiadas SYSTEM "olimpiadas.dtd">
<olimpiadas>
	<año>2012</año>
	<sede>Londres</sede>
	<deporte nombre="Tiro con arco" modalidad="Masculino">
		<ganador>
			<nombre>Furukawa</nombre>
			<pais>Japón</pais>
			<medalla>oro</medalla>
		</ganador>
		<ganador discapacidad="true">
			<nombre>Delgado</nombre>
			<pais>Colombia</pais>
			<medalla>plata</medalla>
		</ganador>
		<ganador discapacidad="true">
			<nombre>Smith</nombre>
			<pais>Inglaterra</pais>
			<medalla>bronce</medalla>
		</ganador>
	</deporte>
	<deporte nombre="Natación" modalidad="Femenino">
		<ganador>
			<nombre>Paulova</nombre>
			<pais>Polonia</pais>
			<medalla>oro</medalla>
		</ganador>
		<ganador>
			<nombre>Fiorella</nombre>
			<pais>Italia</pais>
			<medalla>plata</medalla>
		</ganador>
		<ganador>
			<nombre>Valázquez</nombre>
			<pais>Chile</pais>
			<medalla>bronce</medalla>
		</ganador>
	</deporte>
</olimpiadas>
