=== cedricchristoph/cedric_LND/TRIM2/UD7/Dossier/Practica14/clinica.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="clinica">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="paciente" type="persona" maxOccurs="500"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="persona">
		<xs:sequence>
			<xs:element name="nombre" type="xs:string"/>
			<xs:element name="apellidos" type="xs:string" />
			<xs:element name="visitante" type="persona" minOccurs="0" maxOccurs="2"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== cedricchristoph/cedric_LND/TRIM2/UD7/Dossier/Practica14/clinica.xml
<?xml version="1.0" encoding="UTF-8"?>

<clinica xsi:noNamespaceSchemaLocation="C:\Users\Inf2\Documents\Practica14\clinica.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

	<paciente>
		<nombre>Pedro</nombre>
		<apellidos>Hernández</apellidos>
		<visitante>
			<nombre>Alejandro</nombre>
			<apellidos>Hernández</apellidos>
		</visitante>
		<visitante>
			<nombre>Tom</nombre>
			<apellidos>Tester</apellidos>
		</visitante>
	</paciente>
	
	<paciente>
		<nombre>Alberto</nombre>
		<apellidos>Gil</apellidos>
		<visitante>
			<nombre>Alejandro</nombre>
			<apellidos>Hernández</apellidos>
		</visitante>
		<visitante>
			<nombre>Tom</nombre>
			<apellidos>Tester</apellidos>
		</visitante>
	</paciente>
	
	<paciente>
		<nombre>Alejandra</nombre>
		<apellidos>Pérez</apellidos>
		<visitante>
			<nombre>Alejandro</nombre>
			<apellidos>Hernández</apellidos>
		</visitante>
		<visitante>
			<nombre>Tom</nombre>
			<apellidos>Tester</apellidos>
		</visitante>
	</paciente>
</clinica>
